# Generated by Django 5.2.8 on 2025-12-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('iddepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('torre', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('habitaciones', models.IntegerField(blank=True, null=True)),
                ('banos', models.IntegerField(blank=True, null=True)),
                ('estacionamientos', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='HistorialAccesos',
            fields=[
                ('idhistorial', models.AutoField(primary_key=True, serialize=False)),
                ('idusuario', models.IntegerField(blank=True, null=True)),
                ('idvisitante', models.IntegerField(blank=True, null=True)),
                ('idscanner', models.IntegerField(blank=True, null=True)),
                ('fecha_entrada', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('pendiente', 'Pendiente'), ('Permitido', 'Permitido'), ('Denegado', 'Denegado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_historial', models.BigIntegerField(blank=True, null=True)),
                ('id_scanner', models.BigIntegerField(blank=True, null=True)),
                ('id_usuario', models.BigIntegerField(blank=True, null=True)),
                ('id_visitante', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'db_table': 'historialaccesos',
                'ordering': ['-fecha_entrada', '-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('idscanner', models.AutoField(primary_key=True, serialize=False)),
                ('idusuario', models.IntegerField(blank=True, null=True)),
                ('idvisitante', models.IntegerField(blank=True, null=True)),
                ('foto_capturada', models.TextField(blank=True, null=True)),
                ('tipo_persona', models.CharField(blank=True, choices=[('residente', 'Residente'), ('visitante', 'Visitante')], max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_scanner', models.BigIntegerField(blank=True, null=True)),
                ('id_usuario', models.BigIntegerField(blank=True, null=True)),
                ('id_visitante', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Escaneo',
                'verbose_name_plural': 'Escaneos',
                'db_table': 'scanner',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('idvisitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_visita', models.CharField(max_length=255)),
                ('hora_visita', models.CharField(max_length=255)),
                ('depart_visita', models.CharField(max_length=20)),
                ('foto', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_visitante', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('departamento', models.CharField(max_length=20)),
                ('foto', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.BigIntegerField(blank=True, null=True)),
                ('iddepartamento', models.ForeignKey(blank=True, db_column='iddepartamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
