# Generated by Django 5.2.8 on 2025-12-11 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialaccesos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historialaccesos',
            name='id_historial',
        ),
        migrations.RemoveField(
            model_name='historialaccesos',
            name='id_scanner',
        ),
        migrations.RemoveField(
            model_name='historialaccesos',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='historialaccesos',
            name='id_visitante',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='id_scanner',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='id_visitante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='depart_visita',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='id_visitante',
        ),
        migrations.AddField(
            model_name='visitante',
            name='iddepartamento',
            field=models.ForeignKey(db_column='iddepartamento', default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='iddepartamento',
            field=models.AutoField(db_column='iddepartamento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historialaccesos',
            name='estado',
            field=models.CharField(choices=[('Permitido', 'Permitido'), ('Denegado', 'Denegado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialaccesos',
            name='idhistorial',
            field=models.AutoField(db_column='idhistorial', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historialaccesos',
            name='idscanner',
            field=models.ForeignKey(blank=True, db_column='idscanner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scanner'),
        ),
        migrations.AlterField(
            model_name='historialaccesos',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='historialaccesos',
            name='idvisitante',
            field=models.ForeignKey(blank=True, db_column='idvisitante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visitante'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='idscanner',
            field=models.AutoField(db_column='idscanner', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='idvisitante',
            field=models.ForeignKey(blank=True, db_column='idvisitante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visitante'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='tipo_persona',
            field=models.CharField(choices=[('residente', 'Residente'), ('visitante', 'Visitante')], default='residente', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='iddepartamento',
            field=models.ForeignKey(db_column='iddepartamento', default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idusuario',
            field=models.AutoField(db_column='idusuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='fecha_visita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='hora_visita',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='idvisitante',
            field=models.AutoField(db_column='idvisitante', primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='historialaccesos',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idusuario__isnull', False), ('idvisitante__isnull', True)), models.Q(('idusuario__isnull', True), ('idvisitante__isnull', False)), _connector='OR'), name='chk_acceso_persona'),
        ),
        migrations.AddConstraint(
            model_name='scanner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idusuario__isnull', False), ('idvisitante__isnull', True)), models.Q(('idusuario__isnull', True), ('idvisitante__isnull', False)), _connector='OR'), name='chk_persona'),
        ),
    ]
