# Generated by Django 5.2.8 on 2025-12-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_historialaccesos_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='acepta_foto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='observacion_privacidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PerfilAplicacion',
            fields=[
                ('idperfil', models.AutoField(db_column='idperfil', primary_key=True, serialize=False)),
                ('nombre_aplicacion', models.CharField(default='SafeHome Scanner', max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('contacto_soporte', models.EmailField(blank=True, max_length=150, null=True)),
                ('permitir_registro_sin_foto', models.BooleanField(default=True)),
                ('politica_foto_requerida', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Aplicacion',
                'verbose_name_plural': 'Perfil de Aplicacion',
                'db_table': 'perfilaplicacion',
            },
        ),
    ]
