# Generated by Django 5.2.8 on 2026-06-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_perfilaplicacion_visitante_privacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('idadmin', models.AutoField(db_column='idadmin', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('seguridad', 'Seguridad'), ('supervisor', 'Supervisor')], default='seguridad', max_length=20)),
                ('foto_perfil', models.TextField(blank=True, null=True)),
                ('idioma', models.CharField(default='Español', max_length=10)),
                ('tema', models.CharField(default='Claro', max_length=20)),
                ('autenticacion_2fa', models.BooleanField(default=False)),
                ('tiempo_sesion_horas', models.IntegerField(default=8)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario Administrador',
                'verbose_name_plural': 'Usuarios Administradores',
                'db_table': 'usuarioadmin',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='SesionesAdmin',
            fields=[
                ('idsesion', models.AutoField(db_column='idsesion', primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('idadmin', models.ForeignKey(db_column='idadmin', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='api.usuarioadmin')),
            ],
            options={
                'verbose_name': 'Sesion Administrador',
                'verbose_name_plural': 'Sesiones Administrador',
                'db_table': 'sesionesadmin',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventosSistema',
            fields=[
                ('idevento', models.AutoField(db_column='idevento', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('nivel', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idadmin', models.ForeignKey(blank=True, db_column='idadmin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='api.usuarioadmin')),
            ],
            options={
                'verbose_name': 'Evento del Sistema',
                'verbose_name_plural': 'Eventos del Sistema',
                'db_table': 'eventossistema',
                'ordering': ['-fecha'],
            },
        ),
    ]
