# Generated by Django 5.2.8 on 2026-06-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuarioadmin_sesionesadmin_eventossistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('idconfig', models.AutoField(db_column='idconfig', primary_key=True, serialize=False)),
                ('parametro', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('seguridad', 'Seguridad'), ('camaras', 'Camaras'), ('notificaciones', 'Notificaciones')], default='sistema', max_length=20)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'configuracion',
                'ordering': ['tipo', 'parametro'],
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('idnotificacion', models.AutoField(db_column='idnotificacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Acceso', 'Acceso'), ('Visitante', 'Visitante'), ('Incidente', 'Incidente'), ('Sistema', 'Sistema'), ('Mantenimiento', 'Mantenimiento')], default='Sistema', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
