# Generated by Django 5.2.8 on 2026-06-01 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_configuracion_notificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('idincidente', models.AutoField(db_column='idincidente', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('gravedad', models.CharField(choices=[('BAJA', 'BAJA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA'), ('CRÍTICA', 'CRÍTICA')], default='MEDIA', max_length=20)),
                ('foto_evidencia', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('idscanner', models.ForeignKey(blank=True, db_column='idscanner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scanner')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'db_table': 'incidentes',
                'ordering': ['-fecha'],
            },
        ),
    ]
